version: "3.7"
services:
  core:
    container_name: core
    image: ghcr.io/bitclout/core-obf:latest
    volumes:
    - db:/db
    ports:
    - 17001:17001
    - 17000:17000
    env_file:
    - dev.env
    expose:
    - "17001"
    - "17000"
  frontend:
    container_name: frontend 
    image: ghcr.io/bitclout/frontend:latest
    ports:
    - 8080:8080
    volumes:
    - ./:/app
    env_file:
    - dev.env
    expose:
    - "8080"
  nginx: 
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.dev:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
volumes:
  db:
