version: "3.7"
services:
  core:
    container_name: core
    image: bitcloutnode.azurecr.io/bitclout/core-obf:latest
    volumes:
    - db:/db
    ports:
    - 17001:17001
    - 17000:17000
    env_file:
    - dev.env
    expose:
    - "17001"
    - "17000"
  frontend:
    container_name: frontend 
    image: bitcloutnode.azurecr.io/bitclout/frontend:latest
    ports:
    - 80:80
    volumes:
    - ./:/app
    env_file:
    - dev.env
    expose:
    - "80"
  nginx: 
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.dev:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
      - 443:443
volumes:
  db:
